language: r
warnings_are_errors: false
cache: pacakages
sudo: false

env:
 global:
   - CRAN: https://cran.rstudio.com

notifications:
  email:
    on_success: change
    on_failure: change

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'library(covr); covr::codecov()'
